# Generated by Django 5.2.3 on 2025-09-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0002_alter_user_user_type_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='clinical_app.visit'),
        ),
    ]
