# Generated by Django 5.2.3 on 2025-09-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0004_alter_encounter_encounter_type_alter_visit_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow-up Visit'), ('emergency', 'Emergency'), ('telemedicine', 'Telemedicine'), ('vitals', 'Vitals Check'), ('lab', 'Laboratory'), ('pharmacy', 'Pharmacy'), ('imaging', 'Imaging / Radiology'), ('procedure', 'Minor Procedure'), ('counseling', 'Counseling / Education'), ('triage', 'Triage')], default='outpatient', max_length=20),
        ),
    ]
