# Generated by Django 5.2.3 on 2025-09-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0005_alter_encounter_encounter_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting_triage', 'Waiting for Triage'), ('waiting_consultation', 'Waiting for Consultation'), ('waiting_lab', 'Waiting for Lab'), ('waiting_pharmacy', 'Waiting for Pharmacy'), ('completed', 'Completed')], default='waiting_triage', max_length=30),
        ),
    ]
