# Generated by Django 5.2.3 on 2025-09-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0006_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('waiting_triage', 'Waiting for Triage'), ('triage', 'In Triage'), ('waiting_consultation', 'Waiting for Consultation'), ('consultation', 'In Consultation'), ('waiting_lab', 'Waiting for Lab'), ('lab', 'In Lab'), ('waiting_pharmacy', 'Waiting for Pharmacy'), ('pharmacy', 'In Pharmacy'), ('completed', 'Completed')], default='waiting_triage', max_length=30),
        ),
    ]
