# Generated by Django 5.2.3 on 2025-09-14 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0007_alter_visit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vitalsign',
            name='encounter',
        ),
        migrations.AddField(
            model_name='vitalsign',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='clinical_app.patient'),
        ),
    ]
