# Generated by Django 5.2.3 on 2025-09-14 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0009_insurance_patient_has_insurance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billing',
            options={},
        ),
        migrations.RemoveField(
            model_name='billing',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='bill_date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='bill_id',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='billed_by',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='service_rendered',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='transaction_reference',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='unit_price',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='billing',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_app.encounter'),
        ),
        migrations.AddField(
            model_name='billing',
            name='insurance_covered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='clinical_app.patient'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('insurance', 'Insurance')], max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_on', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clinical_app.billing')),
            ],
        ),
    ]
