# Generated by Django 5.2.3 on 2025-09-15 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0010_alter_billing_options_remove_billing_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitalsign',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='clinical_app.encounter'),
        ),
    ]
