# Generated by Django 5.2.3 on 2025-09-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0011_vitalsign_encounter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='description',
        ),
        migrations.AddField(
            model_name='billing',
            name='service_type',
            field=models.CharField(blank=True, choices=[('consultation', 'Consultation Fee'), ('lab', 'Lab Test'), ('medication', 'Medication'), ('procedure', 'Procedure'), ('registration', 'Registration Fee'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
