# Generated by Django 5.2.3 on 2025-09-16 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0012_remove_billing_description_billing_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='patient',
        ),
        migrations.AddField(
            model_name='billing',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='clinical_app.visit'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='insurance_covered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billing',
            name='service_type',
            field=models.CharField(choices=[('consultation', 'Consultation Fee'), ('lab', 'Lab Test'), ('medication', 'Medication'), ('procedure', 'Procedure'), ('registration', 'Registration Fee'), ('other', 'Other')], default='consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='e.g. MPesa code, receipt number', max_length=100, null=True),
        ),
    ]
