# Generated by Django 5.2.3 on 2025-09-16 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0013_remove_billing_encounter_remove_billing_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20, null=True),
        ),
    ]
