# Generated by Django 5.2.3 on 2025-09-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_app', '0014_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
    ]
